spring:
  datasource:
    url: postgresql://postgres:WsLJYDcqvGGAxtuCOMrTgeoXVgTvLJhl@roundhouse.proxy.rlwy.net:13102/railway
    username: postgres
    password: WsLJYDcqvGGAxtuCOMrTgeoXVgTvLJhl
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
