spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: gft2024
    password: gft2024
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false